
import billing.billingSystem;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN
 */
public class customer extends javax.swing.JFrame {

    /**
     * Creates new form customer
     */
    public customer() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_cnum = new javax.swing.JTextField();
        txt_billnum = new javax.swing.JTextField();
        txt_cname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_cadd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Details :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(527, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 910, 100);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Mobile Number :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(190, 120, 180, 30);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setText("BILL NUMBER :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(220, 220, 160, 30);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setText("Customer Name :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(190, 66, 190, 30);

        txt_cnum.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jPanel2.add(txt_cnum);
        txt_cnum.setBounds(400, 120, 270, 36);

        txt_billnum.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        txt_billnum.setForeground(new java.awt.Color(255, 204, 255));
        txt_billnum.setText("(auto-generated)");
        txt_billnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_billnumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_billnumFocusLost(evt);
            }
        });
        txt_billnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_billnumActionPerformed(evt);
            }
        });
        jPanel2.add(txt_billnum);
        txt_billnum.setBounds(400, 220, 270, 36);

        txt_cname.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jPanel2.add(txt_cname);
        txt_cname.setBounds(400, 70, 270, 36);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(470, 290, 160, 39);

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(210, 290, 160, 39);

        txt_cadd.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jPanel2.add(txt_cadd);
        txt_cadd.setBounds(400, 170, 270, 36);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setText("Address :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(270, 170, 110, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 910, 380);

        setSize(new java.awt.Dimension(925, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         String cname = txt_cname.getText();
        String cnum = txt_cnum.getText();
         String cadd = txt_cadd.getText();
       
      
        if(cname.equals(""))
         {
             JOptionPane.showMessageDialog(null, "ADD A CUSTOMER NAME");
         }
         else if(cnum.equals("")){
               JOptionPane.showMessageDialog(null, "ADD A CUSTOMER NUMBER");
         }
          else if(cadd.equals("")){
               JOptionPane.showMessageDialog(null, "ADD CUSTOMER ADDRESS");
        } else{
               Random ran = new Random();
        int n = ran.nextInt(10000)+1;
        String val=  String.valueOf(n);
        txt_billnum.setText(val);
      String billnum = txt_billnum.getText();
      new billingSystem(cname,cnum,cadd,val).setVisible(true);
        String query = "INSERT INTO customer (cname,cnum,cadd,billnum) VALUES ('"+cname+"','"+cnum+"','"+cadd+"','"+billnum+"')";
          Statement stmt = null;
           try{Connection con = myconnection.getconnection();
            stmt = con.createStatement();
            stmt.executeUpdate(query); 
             
            JOptionPane.showMessageDialog(null,"CUSTOMER DETAILS ADDED");
            
       
           }catch (SQLException ex){
               JOptionPane.showMessageDialog(null,"UNABLE TO ADD CUSTOMER DETAILS\n PLEASE INSERT VALID DETAILS");
           }
        
        
          }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        BandI.main(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_billnumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_billnumFocusGained
        // TODO add your handling code here:
        if(txt_billnum.getText().equals("(auto-generated)")){
            txt_billnum.setText("");
        }
        txt_billnum.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_txt_billnumFocusGained

    private void txt_billnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_billnumFocusLost
        // TODO add your handling code here:
         if(txt_billnum.getText().equals("")){
            txt_billnum.setText("(auto-generated)");
        }
        txt_billnum.setForeground(Color.WHITE);
    }//GEN-LAST:event_txt_billnumFocusLost

    private void txt_billnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_billnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_billnumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_billnum;
    private javax.swing.JTextField txt_cadd;
    private javax.swing.JTextField txt_cname;
    private javax.swing.JTextField txt_cnum;
    // End of variables declaration//GEN-END:variables
}
